echo -e "\e[90m║\e[0m                                      TTTTTTTTTTTTTTTTTTTTTTTHHHHHHHHH     HHHHHHHHHEEEEEEEEEEEEEEEEEEEEEE          OOOOOOOOO     NNNNNNNN        NNNNNNNNEEEEEEEEEEEEEEEEEEEEEE                                      \e[90m║\e[0m";
echo -e "\e[90m║\e[0m         <<<<<<<                      T:::::::::::::::::::::TH:::::::H     H:::::::HE::::::::::::::::::::E        OO:::::::::OO   N:::::::N       N::::::NE::::::::::::::::::::E                      >>>>>>>         \e[90m║\e[0m";
echo -e "\e[90m║\e[0m        <:::::<                       T:::::::::::::::::::::TH:::::::H     H:::::::HE::::::::::::::::::::E      OO:::::::::::::OO N::::::::N      N::::::NE::::::::::::::::::::E                       >:::::>        \e[90m║\e[0m";
echo -e "\e[90m║\e[0m       <:::::<                        T:::::TT:::::::TT:::::THH::::::H     H::::::HHEE::::::EEEEEEEEE::::E     O:::::::OOO:::::::ON:::::::::N     N::::::NEE::::::EEEEEEEEE::::E                        >:::::>       \e[90m║\e[0m";
echo -e "\e[90m║\e[0m      <:::::<                         TTTTTT  T:::::T  TTTTTT  H:::::H     H:::::H    E:::::E       EEEEEE     O::::::O   O::::::ON::::::::::N    N::::::N  E:::::E       EEEEEE                         >:::::>      \e[90m║\e[0m";
echo -e "\e[90m║\e[0m     <:::::<                                  T:::::T          H:::::H     H:::::H    E:::::E                  O:::::O     O:::::ON:::::::::::N   N::::::N  E:::::E                                       >:::::>     \e[90m║\e[0m";
echo -e "\e[90m║\e[0m    <:::::<                                   T:::::T          H::::::HHHHH::::::H    E::::::EEEEEEEEEE        O:::::O     O:::::ON:::::::N::::N  N::::::N  E::::::EEEEEEEEEE                              >:::::>    \e[90m║\e[0m";
echo -e "\e[90m║\e[0m   <:::::<       ---------------              T:::::T          H:::::::::::::::::H    E:::::::::::::::E        O:::::O     O:::::ON::::::N N::::N N::::::N  E:::::::::::::::E         ---------------       >:::::>   \e[90m║\e[0m";
echo -e "\e[90m║\e[0m    <:::::<      -:::::::::::::-              T:::::T          H:::::::::::::::::H    E:::::::::::::::E        O:::::O     O:::::ON::::::N  N::::N:::::::N  E:::::::::::::::E         -:::::::::::::-      >:::::>    \e[90m║\e[0m";
echo -e "\e[90m║\e[0m     <:::::<     ---------------              T:::::T          H::::::HHHHH::::::H    E::::::EEEEEEEEEE        O:::::O     O:::::ON::::::N   N:::::::::::N  E::::::EEEEEEEEEE         ---------------     >:::::>     \e[90m║\e[0m";
echo -e "\e[90m║\e[0m      <:::::<                                 T:::::T          H:::::H     H:::::H    E:::::E                  O:::::O     O:::::ON::::::N    N::::::::::N  E:::::E                                      >:::::>      \e[90m║\e[0m";
echo -e "\e[90m║\e[0m       <:::::<                                T:::::T          H:::::H     H:::::H    E:::::E       EEEEEE     O::::::O   O::::::ON::::::N     N:::::::::N  E:::::E       EEEEEE                        >:::::>       \e[90m║\e[0m";
echo -e "\e[90m║\e[0m        <:::::<                             TT:::::::TT      HH::::::H     H::::::HHEE::::::EEEEEEEE:::::E     O:::::::OOO:::::::ON::::::N      N::::::::NEE::::::EEEEEEEE:::::E                       >:::::>        \e[90m║\e[0m";
echo -e "\e[90m║\e[0m         <<<<<<<                            T:::::::::T      H:::::::H     H:::::::HE::::::::::::::::::::E      OO:::::::::::::OO N::::::N       N:::::::NE::::::::::::::::::::E                      >>>>>>>         \e[90m║\e[0m";
echo -e "\e[90m║\e[0m                                            T:::::::::T      H:::::::H     H:::::::HE::::::::::::::::::::E        OO:::::::::OO   N::::::N        N::::::NE::::::::::::::::::::E                                      \e[90m║\e[0m";
echo -e "\e[90m║\e[0m                                            TTTTTTTTTTT      HHHHHHHHH     HHHHHHHHHEEEEEEEEEEEEEEEEEEEEEE          OOOOOOOOO     NNNNNNNN         NNNNNNNEEEEEEEEEEEEEEEEEEEEEE                                      \e[90m║\e[0m";

